/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material 3 Color Tokens from Stitch
        "on-background": "#1c1c17",
        "surface-container": "#f1ede5",
        "inverse-primary": "#ffb59f",
        "on-tertiary-container": "#fffeff",
        "primary-container": "#d4420a",
        "surface-container-high": "#ece8e0",
        "outline-variant": "#e3bfb4",
        "surface-dim": "#dddad2",
        "primary": "#ac3100",
        "outline": "#8f7067",
        "tertiary": "#5f5d53",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#31302b",
        "on-secondary": "#ffffff",
        "background": "#fdf9f1",
        "tertiary-fixed": "#e7e2d5",
        "on-surface": "#1c1c17",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e6e2da",
        "on-secondary-container": "#2a687d",
        "secondary-fixed-dim": "#94cfe7",
        "secondary": "#27667b",
        "on-tertiary-fixed": "#1d1c14",
        "primary-fixed": "#ffdbd0",
        "primary-fixed-dim": "#ffb59f",
        "surface-tint": "#ae3100",
        "on-error-container": "#93000a",
        "surface-bright": "#fdf9f1",
        "tertiary-container": "#78766b",
        "on-primary-fixed": "#3a0a00",
        "on-primary": "#ffffff",
        "on-surface-variant": "#5a4139",
        "inverse-on-surface": "#f4f0e8",
        "tertiary-fixed-dim": "#cac6b9",
        "surface": "#fdf9f1",
        "secondary-fixed": "#b9eaff",
        "surface-container-low": "#f7f3eb",
        "error": "#ba1a1a",
        "on-primary-container": "#fffeff",
        "on-primary-fixed-variant": "#852400",
        "on-tertiary-fixed-variant": "#49473d",
        "surface-variant": "#e6e2da",
        "secondary-container": "#aae5fe",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#004d62",
        "on-secondary-fixed": "#001f29",
        "error-container": "#ffdad6",
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        11: '0.6875rem',
        12: '0.75rem',
        13: '0.8125rem',
        14: '0.875rem',
        15: '0.9375rem',
        16: '1rem',
        18: '1.125rem',
        20: '1.25rem',
        24: '1.5rem',
        32: '2rem',
        48: '3rem',
        64: '4rem',
        80: '5rem',
        96: '6rem',
        120: '7.5rem',
      },
      spacing: {
        4: '0.25rem',
        8: '0.5rem',
        12: '0.75rem',
        16: '1rem',
        24: '1.5rem',
        32: '2rem',
        40: '2.5rem',
        48: '3rem',
        56: '3.5rem',
        64: '4rem',
        72: '4.5rem',
        80: '5rem',
        96: '6rem',
        128: '8rem',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        '3xl': '1rem',
        full: '9999px',
      },
      animation: {
        'marquee': 'marquee 30s linear infinite',
        'marquee-reverse': 'marquee-reverse 30s linear infinite',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'marquee-reverse': {
          '0%': { transform: 'translateX(-50%)' },
          '100%': { transform: 'translateX(0)' },
        },
      },
    },
  },
  plugins: [],
}
